#!/usr/bin/env bash

# Initialization for interactive shells (even login shells, since we source it from .bash_profile)

if [ -f "$HOME/.cargo/env" ]; then
	. "$HOME/.cargo/env"
fi

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

export PATH="$HOME/.console-ninja/.bin:$PATH"

export EDITOR="nvim"

function br {
	local cmd cmd_file code
	cmd_file=$(mktemp)
	if broot --outcmd "$cmd_file" "$@"; then
		cmd=$(<"$cmd_file")
		command rm -f "$cmd_file"
		eval "$cmd"
	else
		code=$?
		command rm -f "$cmd_file"
		return "$code"
	fi
}

eval "$(starship init bash)"
